### ISSUE TITLE
Results array returned empty

### ISSUE THREAD

**Issue by sminoj** [steinmns/Plex-Auto-Downloader#1]
When beginning a search for a torrent, the search_start begins and returns a search_id but when fetching the search_status, the search is 'Running'. I attempted to loop until the total number of torrents returned was > 0 but ultimately ended stuck in the loop.

```
# Testing the search function
search_term = 'no country for old men'
results = qbit.search(search_term=search_term, num_results=50)
# Raise an exception if results array is empty
if results == []:
    raise Exception('Empty array for "results"')
else:
    # Else print out the search results
    print('The results are: %s\n' % results)
```

Added an exception when the results array is empty to quickly see if the search function is working correctly or not.

**Comment by steinmns** [comment]
Fixed 2/11/2020. Now returns list of results properly.
